// phone-database.ts — Dataset estático de smartphones comunes en LATAM
// Para agregar nuevos modelos: añadir entradas { brand, model } al array.

export interface PhoneEntry {
  brand: string;
  model: string;
}

export const PHONE_DATABASE: PhoneEntry[] = [
  // ── Apple iPhone ─────────────────────────────────────────────────────────
  { brand: "Apple", model: "iPhone 6" },
  { brand: "Apple", model: "iPhone 6 Plus" },
  { brand: "Apple", model: "iPhone 6s" },
  { brand: "Apple", model: "iPhone 6s Plus" },
  { brand: "Apple", model: "iPhone 7" },
  { brand: "Apple", model: "iPhone 7 Plus" },
  { brand: "Apple", model: "iPhone 8" },
  { brand: "Apple", model: "iPhone 8 Plus" },
  { brand: "Apple", model: "iPhone X" },
  { brand: "Apple", model: "iPhone XR" },
  { brand: "Apple", model: "iPhone XS" },
  { brand: "Apple", model: "iPhone XS Max" },
  { brand: "Apple", model: "iPhone 11" },
  { brand: "Apple", model: "iPhone 11 Pro" },
  { brand: "Apple", model: "iPhone 11 Pro Max" },
  { brand: "Apple", model: "iPhone SE (2020)" },
  { brand: "Apple", model: "iPhone 12" },
  { brand: "Apple", model: "iPhone 12 Mini" },
  { brand: "Apple", model: "iPhone 12 Pro" },
  { brand: "Apple", model: "iPhone 12 Pro Max" },
  { brand: "Apple", model: "iPhone 13" },
  { brand: "Apple", model: "iPhone 13 Mini" },
  { brand: "Apple", model: "iPhone 13 Pro" },
  { brand: "Apple", model: "iPhone 13 Pro Max" },
  { brand: "Apple", model: "iPhone SE (2022)" },
  { brand: "Apple", model: "iPhone 14" },
  { brand: "Apple", model: "iPhone 14 Plus" },
  { brand: "Apple", model: "iPhone 14 Pro" },
  { brand: "Apple", model: "iPhone 14 Pro Max" },
  { brand: "Apple", model: "iPhone 15" },
  { brand: "Apple", model: "iPhone 15 Plus" },
  { brand: "Apple", model: "iPhone 15 Pro" },
  { brand: "Apple", model: "iPhone 15 Pro Max" },
  { brand: "Apple", model: "iPhone 16" },
  { brand: "Apple", model: "iPhone 16 Plus" },
  { brand: "Apple", model: "iPhone 16 Pro" },
  { brand: "Apple", model: "iPhone 16 Pro Max" },
  { brand: "Apple", model: "iPhone SE (2024)" },

  // ── Samsung Galaxy A Series ───────────────────────────────────────────────
  { brand: "Samsung", model: "Galaxy A02" },
  { brand: "Samsung", model: "Galaxy A02s" },
  { brand: "Samsung", model: "Galaxy A03" },
  { brand: "Samsung", model: "Galaxy A03s" },
  { brand: "Samsung", model: "Galaxy A03 Core" },
  { brand: "Samsung", model: "Galaxy A04" },
  { brand: "Samsung", model: "Galaxy A04s" },
  { brand: "Samsung", model: "Galaxy A04e" },
  { brand: "Samsung", model: "Galaxy A05" },
  { brand: "Samsung", model: "Galaxy A05s" },
  { brand: "Samsung", model: "Galaxy A06" },
  { brand: "Samsung", model: "Galaxy A10" },
  { brand: "Samsung", model: "Galaxy A10s" },
  { brand: "Samsung", model: "Galaxy A10e" },
  { brand: "Samsung", model: "Galaxy A11" },
  { brand: "Samsung", model: "Galaxy A12" },
  { brand: "Samsung", model: "Galaxy A13" },
  { brand: "Samsung", model: "Galaxy A13 5G" },
  { brand: "Samsung", model: "Galaxy A14" },
  { brand: "Samsung", model: "Galaxy A14 5G" },
  { brand: "Samsung", model: "Galaxy A15" },
  { brand: "Samsung", model: "Galaxy A15 5G" },
  { brand: "Samsung", model: "Galaxy A16" },
  { brand: "Samsung", model: "Galaxy A16 5G" },
  { brand: "Samsung", model: "Galaxy A20" },
  { brand: "Samsung", model: "Galaxy A20s" },
  { brand: "Samsung", model: "Galaxy A21s" },
  { brand: "Samsung", model: "Galaxy A22" },
  { brand: "Samsung", model: "Galaxy A22 5G" },
  { brand: "Samsung", model: "Galaxy A23" },
  { brand: "Samsung", model: "Galaxy A23 5G" },
  { brand: "Samsung", model: "Galaxy A24" },
  { brand: "Samsung", model: "Galaxy A25 5G" },
  { brand: "Samsung", model: "Galaxy A30" },
  { brand: "Samsung", model: "Galaxy A30s" },
  { brand: "Samsung", model: "Galaxy A31" },
  { brand: "Samsung", model: "Galaxy A32" },
  { brand: "Samsung", model: "Galaxy A32 5G" },
  { brand: "Samsung", model: "Galaxy A33 5G" },
  { brand: "Samsung", model: "Galaxy A34 5G" },
  { brand: "Samsung", model: "Galaxy A35 5G" },
  { brand: "Samsung", model: "Galaxy A36 5G" },
  { brand: "Samsung", model: "Galaxy A40" },
  { brand: "Samsung", model: "Galaxy A41" },
  { brand: "Samsung", model: "Galaxy A42 5G" },
  { brand: "Samsung", model: "Galaxy A50" },
  { brand: "Samsung", model: "Galaxy A50s" },
  { brand: "Samsung", model: "Galaxy A51" },
  { brand: "Samsung", model: "Galaxy A51 5G" },
  { brand: "Samsung", model: "Galaxy A52" },
  { brand: "Samsung", model: "Galaxy A52s 5G" },
  { brand: "Samsung", model: "Galaxy A53 5G" },
  { brand: "Samsung", model: "Galaxy A54 5G" },
  { brand: "Samsung", model: "Galaxy A55 5G" },
  { brand: "Samsung", model: "Galaxy A56 5G" },
  { brand: "Samsung", model: "Galaxy A70" },
  { brand: "Samsung", model: "Galaxy A71" },
  { brand: "Samsung", model: "Galaxy A72" },
  { brand: "Samsung", model: "Galaxy A73 5G" },

  // ── Samsung Galaxy S Series ───────────────────────────────────────────────
  { brand: "Samsung", model: "Galaxy S10" },
  { brand: "Samsung", model: "Galaxy S10e" },
  { brand: "Samsung", model: "Galaxy S10+" },
  { brand: "Samsung", model: "Galaxy S20" },
  { brand: "Samsung", model: "Galaxy S20+" },
  { brand: "Samsung", model: "Galaxy S20 Ultra" },
  { brand: "Samsung", model: "Galaxy S20 FE" },
  { brand: "Samsung", model: "Galaxy S21" },
  { brand: "Samsung", model: "Galaxy S21+" },
  { brand: "Samsung", model: "Galaxy S21 Ultra" },
  { brand: "Samsung", model: "Galaxy S21 FE" },
  { brand: "Samsung", model: "Galaxy S22" },
  { brand: "Samsung", model: "Galaxy S22+" },
  { brand: "Samsung", model: "Galaxy S22 Ultra" },
  { brand: "Samsung", model: "Galaxy S23" },
  { brand: "Samsung", model: "Galaxy S23+" },
  { brand: "Samsung", model: "Galaxy S23 Ultra" },
  { brand: "Samsung", model: "Galaxy S23 FE" },
  { brand: "Samsung", model: "Galaxy S24" },
  { brand: "Samsung", model: "Galaxy S24+" },
  { brand: "Samsung", model: "Galaxy S24 Ultra" },
  { brand: "Samsung", model: "Galaxy S24 FE" },
  { brand: "Samsung", model: "Galaxy S25" },
  { brand: "Samsung", model: "Galaxy S25+" },
  { brand: "Samsung", model: "Galaxy S25 Ultra" },

  // ── Samsung Galaxy M Series ───────────────────────────────────────────────
  { brand: "Samsung", model: "Galaxy M02s" },
  { brand: "Samsung", model: "Galaxy M12" },
  { brand: "Samsung", model: "Galaxy M13" },
  { brand: "Samsung", model: "Galaxy M14 5G" },
  { brand: "Samsung", model: "Galaxy M15 5G" },
  { brand: "Samsung", model: "Galaxy M21" },
  { brand: "Samsung", model: "Galaxy M22" },
  { brand: "Samsung", model: "Galaxy M23 5G" },
  { brand: "Samsung", model: "Galaxy M31" },
  { brand: "Samsung", model: "Galaxy M32" },
  { brand: "Samsung", model: "Galaxy M33 5G" },
  { brand: "Samsung", model: "Galaxy M34 5G" },

  // ── Samsung Galaxy Note ───────────────────────────────────────────────────
  { brand: "Samsung", model: "Galaxy Note 10" },
  { brand: "Samsung", model: "Galaxy Note 10+" },
  { brand: "Samsung", model: "Galaxy Note 20" },
  { brand: "Samsung", model: "Galaxy Note 20 Ultra" },

  // ── Samsung Galaxy Z Series ───────────────────────────────────────────────
  { brand: "Samsung", model: "Galaxy Z Flip3" },
  { brand: "Samsung", model: "Galaxy Z Flip4" },
  { brand: "Samsung", model: "Galaxy Z Flip5" },
  { brand: "Samsung", model: "Galaxy Z Flip6" },
  { brand: "Samsung", model: "Galaxy Z Fold3" },
  { brand: "Samsung", model: "Galaxy Z Fold4" },
  { brand: "Samsung", model: "Galaxy Z Fold5" },
  { brand: "Samsung", model: "Galaxy Z Fold6" },

  // ── Xiaomi Redmi ─────────────────────────────────────────────────────────
  { brand: "Xiaomi", model: "Redmi 9" },
  { brand: "Xiaomi", model: "Redmi 9A" },
  { brand: "Xiaomi", model: "Redmi 9C" },
  { brand: "Xiaomi", model: "Redmi 9T" },
  { brand: "Xiaomi", model: "Redmi 10" },
  { brand: "Xiaomi", model: "Redmi 10A" },
  { brand: "Xiaomi", model: "Redmi 10C" },
  { brand: "Xiaomi", model: "Redmi 12" },
  { brand: "Xiaomi", model: "Redmi 12C" },
  { brand: "Xiaomi", model: "Redmi 13" },
  { brand: "Xiaomi", model: "Redmi 13C" },
  { brand: "Xiaomi", model: "Redmi Note 9" },
  { brand: "Xiaomi", model: "Redmi Note 9 Pro" },
  { brand: "Xiaomi", model: "Redmi Note 9S" },
  { brand: "Xiaomi", model: "Redmi Note 10" },
  { brand: "Xiaomi", model: "Redmi Note 10 Pro" },
  { brand: "Xiaomi", model: "Redmi Note 10S" },
  { brand: "Xiaomi", model: "Redmi Note 11" },
  { brand: "Xiaomi", model: "Redmi Note 11 Pro" },
  { brand: "Xiaomi", model: "Redmi Note 11S" },
  { brand: "Xiaomi", model: "Redmi Note 12" },
  { brand: "Xiaomi", model: "Redmi Note 12 Pro" },
  { brand: "Xiaomi", model: "Redmi Note 12 Pro+" },
  { brand: "Xiaomi", model: "Redmi Note 13" },
  { brand: "Xiaomi", model: "Redmi Note 13 Pro" },
  { brand: "Xiaomi", model: "Redmi Note 13 Pro+" },
  { brand: "Xiaomi", model: "Redmi Note 14" },
  { brand: "Xiaomi", model: "Redmi Note 14 Pro" },
  { brand: "Xiaomi", model: "Redmi Note 14 Pro+" },

  // ── Xiaomi POCO ──────────────────────────────────────────────────────────
  { brand: "Xiaomi", model: "POCO M3" },
  { brand: "Xiaomi", model: "POCO M4 Pro" },
  { brand: "Xiaomi", model: "POCO M5" },
  { brand: "Xiaomi", model: "POCO M5s" },
  { brand: "Xiaomi", model: "POCO M6 Pro" },
  { brand: "Xiaomi", model: "POCO X3" },
  { brand: "Xiaomi", model: "POCO X3 Pro" },
  { brand: "Xiaomi", model: "POCO X4 Pro 5G" },
  { brand: "Xiaomi", model: "POCO X5" },
  { brand: "Xiaomi", model: "POCO X5 Pro" },
  { brand: "Xiaomi", model: "POCO X6" },
  { brand: "Xiaomi", model: "POCO X6 Pro" },
  { brand: "Xiaomi", model: "POCO F3" },
  { brand: "Xiaomi", model: "POCO F4" },
  { brand: "Xiaomi", model: "POCO F5" },
  { brand: "Xiaomi", model: "POCO F6 Pro" },

  // ── Xiaomi Mi / Xiaomi serie ─────────────────────────────────────────────
  { brand: "Xiaomi", model: "Xiaomi 11T" },
  { brand: "Xiaomi", model: "Xiaomi 11T Pro" },
  { brand: "Xiaomi", model: "Xiaomi 12" },
  { brand: "Xiaomi", model: "Xiaomi 12 Pro" },
  { brand: "Xiaomi", model: "Xiaomi 13" },
  { brand: "Xiaomi", model: "Xiaomi 13 Pro" },
  { brand: "Xiaomi", model: "Xiaomi 14" },
  { brand: "Xiaomi", model: "Xiaomi 14 Pro" },
  { brand: "Xiaomi", model: "Xiaomi 14 Ultra" },

  // ── Motorola Moto G ───────────────────────────────────────────────────────
  { brand: "Motorola", model: "Moto G04" },
  { brand: "Motorola", model: "Moto G04s" },
  { brand: "Motorola", model: "Moto G05" },
  { brand: "Motorola", model: "Moto G14" },
  { brand: "Motorola", model: "Moto G15" },
  { brand: "Motorola", model: "Moto G24" },
  { brand: "Motorola", model: "Moto G24 Power" },
  { brand: "Motorola", model: "Moto G25" },
  { brand: "Motorola", model: "Moto G31" },
  { brand: "Motorola", model: "Moto G32" },
  { brand: "Motorola", model: "Moto G34 5G" },
  { brand: "Motorola", model: "Moto G35 5G" },
  { brand: "Motorola", model: "Moto G42" },
  { brand: "Motorola", model: "Moto G50" },
  { brand: "Motorola", model: "Moto G52" },
  { brand: "Motorola", model: "Moto G53 5G" },
  { brand: "Motorola", model: "Moto G54 5G" },
  { brand: "Motorola", model: "Moto G55 5G" },
  { brand: "Motorola", model: "Moto G60" },
  { brand: "Motorola", model: "Moto G62 5G" },
  { brand: "Motorola", model: "Moto G71 5G" },
  { brand: "Motorola", model: "Moto G72" },
  { brand: "Motorola", model: "Moto G73 5G" },
  { brand: "Motorola", model: "Moto G84 5G" },
  { brand: "Motorola", model: "Moto G85 5G" },
  { brand: "Motorola", model: "Moto G100" },
  { brand: "Motorola", model: "Moto G200 5G" },

  // ── Motorola Moto E ───────────────────────────────────────────────────────
  { brand: "Motorola", model: "Moto E6i" },
  { brand: "Motorola", model: "Moto E6 Play" },
  { brand: "Motorola", model: "Moto E7" },
  { brand: "Motorola", model: "Moto E7 Power" },
  { brand: "Motorola", model: "Moto E20" },
  { brand: "Motorola", model: "Moto E22" },
  { brand: "Motorola", model: "Moto E32" },
  { brand: "Motorola", model: "Moto E40" },

  // ── Motorola Edge ─────────────────────────────────────────────────────────
  { brand: "Motorola", model: "Moto Edge 20" },
  { brand: "Motorola", model: "Moto Edge 20 Pro" },
  { brand: "Motorola", model: "Moto Edge 30" },
  { brand: "Motorola", model: "Moto Edge 30 Neo" },
  { brand: "Motorola", model: "Moto Edge 30 Pro" },
  { brand: "Motorola", model: "Moto Edge 40" },
  { brand: "Motorola", model: "Moto Edge 40 Neo" },
  { brand: "Motorola", model: "Moto Edge 40 Pro" },
  { brand: "Motorola", model: "Moto Edge 50" },
  { brand: "Motorola", model: "Moto Edge 50 Neo" },
  { brand: "Motorola", model: "Moto Edge 50 Pro" },
  { brand: "Motorola", model: "Moto Edge 50 Ultra" },
  { brand: "Motorola", model: "Motorola Razr 40" },
  { brand: "Motorola", model: "Motorola Razr 40 Ultra" },
  { brand: "Motorola", model: "Motorola Razr+ 2024" },

  // ── Huawei ───────────────────────────────────────────────────────────────
  { brand: "Huawei", model: "P30 Lite" },
  { brand: "Huawei", model: "P30" },
  { brand: "Huawei", model: "P30 Pro" },
  { brand: "Huawei", model: "P40 Lite" },
  { brand: "Huawei", model: "P40" },
  { brand: "Huawei", model: "P40 Pro" },
  { brand: "Huawei", model: "P50 Lite" },
  { brand: "Huawei", model: "P50" },
  { brand: "Huawei", model: "Nova 5T" },
  { brand: "Huawei", model: "Nova 7i" },
  { brand: "Huawei", model: "Nova 8i" },
  { brand: "Huawei", model: "Nova 9" },
  { brand: "Huawei", model: "Nova 10" },
  { brand: "Huawei", model: "Nova 11" },
  { brand: "Huawei", model: "Nova 12" },
  { brand: "Huawei", model: "Y6p" },
  { brand: "Huawei", model: "Y7a" },
  { brand: "Huawei", model: "Y8p" },
  { brand: "Huawei", model: "Y9a" },
  { brand: "Huawei", model: "Y9 Prime 2019" },
  { brand: "Huawei", model: "Mate 40 Pro" },
  { brand: "Huawei", model: "Mate 50 Pro" },

  // ── OPPO ─────────────────────────────────────────────────────────────────
  { brand: "OPPO", model: "A15" },
  { brand: "OPPO", model: "A16" },
  { brand: "OPPO", model: "A17" },
  { brand: "OPPO", model: "A18" },
  { brand: "OPPO", model: "A38" },
  { brand: "OPPO", model: "A57" },
  { brand: "OPPO", model: "A58" },
  { brand: "OPPO", model: "A74" },
  { brand: "OPPO", model: "A78" },
  { brand: "OPPO", model: "A96" },
  { brand: "OPPO", model: "Reno 5" },
  { brand: "OPPO", model: "Reno 6" },
  { brand: "OPPO", model: "Reno 7" },
  { brand: "OPPO", model: "Reno 8" },
  { brand: "OPPO", model: "Reno 10" },
  { brand: "OPPO", model: "Reno 11" },
  { brand: "OPPO", model: "Reno 12" },
  { brand: "OPPO", model: "Find X5" },
  { brand: "OPPO", model: "Find X6" },
  { brand: "OPPO", model: "Find X7" },

  // ── Vivo ──────────────────────────────────────────────────────────────────
  { brand: "Vivo", model: "Y02" },
  { brand: "Vivo", model: "Y11s" },
  { brand: "Vivo", model: "Y15s" },
  { brand: "Vivo", model: "Y16" },
  { brand: "Vivo", model: "Y17s" },
  { brand: "Vivo", model: "Y21" },
  { brand: "Vivo", model: "Y22" },
  { brand: "Vivo", model: "Y27" },
  { brand: "Vivo", model: "Y33s" },
  { brand: "Vivo", model: "Y35" },
  { brand: "Vivo", model: "Y36" },
  { brand: "Vivo", model: "Y52 5G" },
  { brand: "Vivo", model: "V21" },
  { brand: "Vivo", model: "V23" },
  { brand: "Vivo", model: "V25" },
  { brand: "Vivo", model: "V27" },
  { brand: "Vivo", model: "V29" },
  { brand: "Vivo", model: "X70 Pro" },
  { brand: "Vivo", model: "X80 Pro" },

  // ── Realme ────────────────────────────────────────────────────────────────
  { brand: "Realme", model: "C11" },
  { brand: "Realme", model: "C21" },
  { brand: "Realme", model: "C25s" },
  { brand: "Realme", model: "C30" },
  { brand: "Realme", model: "C33" },
  { brand: "Realme", model: "C35" },
  { brand: "Realme", model: "C51" },
  { brand: "Realme", model: "C53" },
  { brand: "Realme", model: "C55" },
  { brand: "Realme", model: "C67" },
  { brand: "Realme", model: "8" },
  { brand: "Realme", model: "8 Pro" },
  { brand: "Realme", model: "9" },
  { brand: "Realme", model: "9 Pro" },
  { brand: "Realme", model: "9 Pro+" },
  { brand: "Realme", model: "10" },
  { brand: "Realme", model: "10 Pro" },
  { brand: "Realme", model: "10 Pro+" },
  { brand: "Realme", model: "11" },
  { brand: "Realme", model: "11 Pro" },
  { brand: "Realme", model: "11 Pro+" },
  { brand: "Realme", model: "12" },
  { brand: "Realme", model: "12 Pro" },
  { brand: "Realme", model: "12 Pro+" },
  { brand: "Realme", model: "GT 2" },
  { brand: "Realme", model: "GT 3" },
  { brand: "Realme", model: "GT Neo 3" },
  { brand: "Realme", model: "GT Neo 5" },

  // ── OnePlus ───────────────────────────────────────────────────────────────
  { brand: "OnePlus", model: "Nord CE 2 Lite" },
  { brand: "OnePlus", model: "Nord CE 3 Lite" },
  { brand: "OnePlus", model: "Nord CE 4 Lite" },
  { brand: "OnePlus", model: "Nord 2T" },
  { brand: "OnePlus", model: "Nord 3" },
  { brand: "OnePlus", model: "Nord 4" },
  { brand: "OnePlus", model: "10T" },
  { brand: "OnePlus", model: "10 Pro" },
  { brand: "OnePlus", model: "11" },
  { brand: "OnePlus", model: "11R" },
  { brand: "OnePlus", model: "12" },
  { brand: "OnePlus", model: "12R" },
  { brand: "OnePlus", model: "Open" },

  // ── Nokia ─────────────────────────────────────────────────────────────────
  { brand: "Nokia", model: "C12" },
  { brand: "Nokia", model: "C21 Plus" },
  { brand: "Nokia", model: "C32" },
  { brand: "Nokia", model: "G11" },
  { brand: "Nokia", model: "G21" },
  { brand: "Nokia", model: "G22" },
  { brand: "Nokia", model: "G42 5G" },
  { brand: "Nokia", model: "G60 5G" },
  { brand: "Nokia", model: "X30 5G" },

  // ── Tecno ─────────────────────────────────────────────────────────────────
  { brand: "Tecno", model: "Spark 8C" },
  { brand: "Tecno", model: "Spark 9" },
  { brand: "Tecno", model: "Spark 9T" },
  { brand: "Tecno", model: "Spark 10" },
  { brand: "Tecno", model: "Spark 10 Pro" },
  { brand: "Tecno", model: "Spark 20" },
  { brand: "Tecno", model: "Spark 20 Pro" },
  { brand: "Tecno", model: "Pop 6 Pro" },
  { brand: "Tecno", model: "Pop 7 Pro" },
  { brand: "Tecno", model: "Camon 19" },
  { brand: "Tecno", model: "Camon 20" },
  { brand: "Tecno", model: "Camon 30" },
  { brand: "Tecno", model: "Pova 4" },
  { brand: "Tecno", model: "Pova 5" },
  { brand: "Tecno", model: "Phantom X2" },

  // ── Infinix ───────────────────────────────────────────────────────────────
  { brand: "Infinix", model: "Hot 11s" },
  { brand: "Infinix", model: "Hot 12" },
  { brand: "Infinix", model: "Hot 20i" },
  { brand: "Infinix", model: "Hot 30" },
  { brand: "Infinix", model: "Hot 30i" },
  { brand: "Infinix", model: "Hot 40" },
  { brand: "Infinix", model: "Note 11" },
  { brand: "Infinix", model: "Note 12" },
  { brand: "Infinix", model: "Note 30" },
  { brand: "Infinix", model: "Note 40" },
  { brand: "Infinix", model: "Smart 6" },
  { brand: "Infinix", model: "Smart 7" },
  { brand: "Infinix", model: "Zero 5G" },
  { brand: "Infinix", model: "Zero 30" },

  // ── TCL ───────────────────────────────────────────────────────────────────
  { brand: "TCL", model: "20 SE" },
  { brand: "TCL", model: "20 Pro 5G" },
  { brand: "TCL", model: "30 SE" },
  { brand: "TCL", model: "305" },
  { brand: "TCL", model: "306" },
  { brand: "TCL", model: "403" },
  { brand: "TCL", model: "408" },
  { brand: "TCL", model: "501" },
  { brand: "TCL", model: "505" },

  // ── Alcatel ───────────────────────────────────────────────────────────────
  { brand: "Alcatel", model: "1B (2022)" },
  { brand: "Alcatel", model: "3L (2021)" },
  { brand: "Alcatel", model: "1L Pro" },
  { brand: "Alcatel", model: "3X" },
  { brand: "Alcatel", model: "5V" },

  // ── ZTE ───────────────────────────────────────────────────────────────────
  { brand: "ZTE", model: "Blade A31" },
  { brand: "ZTE", model: "Blade A52" },
  { brand: "ZTE", model: "Blade A72" },
  { brand: "ZTE", model: "Blade V30" },
  { brand: "ZTE", model: "Blade V40" },
  { brand: "ZTE", model: "Blade V50" },
];

/** Lista de marcas únicas para el selector de marcas */
export const PHONE_BRANDS = [...new Set(PHONE_DATABASE.map((p) => p.brand))].sort();

/**
 * Busca modelos para una marca dada, filtrados por query.
 * Si brand es vacío, retorna vacío (primero se debe seleccionar una marca).
 */
export function searchPhoneModels(brand: string, query: string): string[] {
  if (!brand) return [];
  const q = query.toLowerCase().trim();
  return PHONE_DATABASE
    .filter((p) => p.brand === brand && (!q || p.model.toLowerCase().includes(q)))
    .map((p) => p.model);
}

/**
 * Verifica si un texto dado es una marca reconocida en el dataset.
 */
export function isKnownBrand(brand: string): boolean {
  return PHONE_BRANDS.includes(brand);
}
